osx_image: xcode8.3
language: objective-c
xcode_project: NavitiaSDKUX.xcodeproj
xcode_scheme: NavitiaSDKUX
xcode_sdk: iphonesimulator9.3
env:
  global:
    - FRAMEWORK_NAME=NavitiaSDKUX
cache:
  directories:
    - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - travis_wait carthage bootstrap --platform iOS --cache-builds
script:
  - travis_wait carthage build --no-skip-current --platform iOS --cache-builds
before_deploy:
  - carthage archive $FRAMEWORK_NAME
